import React, { useEffect, useMemo, useState } from 'react';
import { Save } from 'lucide-react';
import { api } from '../lib/api';
import { todayCairo } from '../lib/date';
import type { AttendanceStatus, Student, StudentAttendanceRecord } from '../types';

const statusLabels: Record<AttendanceStatus,string>={Present:'حاضر',Late:'متأخر',AbsentExcused:'غائب بعذر',AbsentUnexcused:'غائب بدون عذر',Permission:'استئذان'};
export function AttendancePage(){const[students,setStudents]=useState<Student[]>([]);const[date,setDate]=useState(todayCairo());const[classroom,setClassroom]=useState('ALL');const[records,setRecords]=useState<Record<string,StudentAttendanceRecord>>({});const[msg,setMsg]=useState<string|null>(null);
useEffect(()=>{Promise.all([api<Student[]>('listStudents'),api<StudentAttendanceRecord[]>('listStudentAttendance',{date})]).then(([s,r])=>{setStudents(s);setRecords(Object.fromEntries(r.map(x=>[x.studentId,x])))})},[date]);
const classes=useMemo(()=>Array.from(new Set(students.map(s=>s.classroomName))),[students]);const visible=students.filter(s=>s.status==='Active'&&(classroom==='ALL'||s.classroomName===classroom));
const setStatus=(s:Student,status:AttendanceStatus)=>setRecords(p=>({...p,[s.id]:{id:p[s.id]?.id||`ATT-${s.id}-${date}`,studentId:s.id,date,status,lateMinutes:status==='Late'?p[s.id]?.lateMinutes||10:0,notes:p[s.id]?.notes}}));
const save=async()=>{const list=visible.map(s=>records[s.id]||{id:`ATT-${s.id}-${date}`,studentId:s.id,date,status:'Present' as AttendanceStatus});await api('saveStudentAttendanceBulk',{records:list});setMsg('تم حفظ حضور اليوم بنجاح.');setTimeout(()=>setMsg(null),2500)};
return <><div className="page-header"><div><h1>الحضور والغياب اليومي</h1><p>رصد الغياب والتأخير والاستئذان بدون حضور حصصي منفصل.</p></div><button className="btn btn-primary" onClick={save}><Save size={16}/> حفظ اليوم</button></div>{msg&&<div className="alert alert-success" style={{marginBottom:12}}>{msg}</div>}<div className="card panel"><div className="toolbar"><div className="field"><label>التاريخ</label><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>الفصل</label><select className="select" value={classroom} onChange={e=>setClassroom(e.target.value)}><option value="ALL">كل الفصول</option>{classes.map(c=><option key={c}>{c}</option>)}</select></div></div><div className="table-wrap"><table><thead><tr><th>الطالب</th><th>الفصل</th><th>الحالة</th><th>التأخير</th><th>ملاحظات</th></tr></thead><tbody>{visible.map(s=>{const r: Partial<StudentAttendanceRecord> & { status: AttendanceStatus } = records[s.id] || {status:'Present' as AttendanceStatus};return <tr key={s.id}><td><strong>{s.name}</strong><div className="small muted">{s.studentCode}</div></td><td>{s.classroomName}</td><td><select className="select" value={r.status} onChange={e=>setStatus(s,e.target.value as AttendanceStatus)}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td>{r.status==='Late'?<input className="input" type="number" min="0" value={r.lateMinutes||0} onChange={e=>setRecords(p=>({...p,[s.id]:{...(p[s.id]||{id:`ATT-${s.id}-${date}`,studentId:s.id,date,status:'Late'}),lateMinutes:Number(e.target.value)}}))}/>:<span className="muted">—</span>}</td><td><input className="input" value={r.notes||''} onChange={e=>setRecords(p=>({...p,[s.id]:{...(p[s.id]||{id:`ATT-${s.id}-${date}`,studentId:s.id,date,status:'Present'}),notes:e.target.value}}))}/></td></tr>})}</tbody></table></div></div></>}
