import React, { useEffect, useMemo, useState } from 'react';
import { KeyRound, Plus, Search } from 'lucide-react';
import { api } from '../lib/api';
import type { Employee } from '../types';
import { Modal } from '../components/Modal';

const emptyEmployee: Employee = { id:'', employeeCode:'', name:'', jobTitle:'', department:'', status:'Active', isTeacher:false, teacherCode:'' };

export function EmployeesPage() {
  const [items,setItems]=useState<Employee[]>([]); const [query,setQuery]=useState(''); const [editing,setEditing]=useState<Employee|null>(null); const [pinEmp,setPinEmp]=useState<Employee|null>(null); const [error,setError]=useState<string|null>(null);
  const load=()=>api<Employee[]>('listEmployees').then(setItems).catch(e=>setError(e.message)); useEffect(load,[]);
  const filtered=useMemo(()=>items.filter(e=>!query||`${e.name} ${e.employeeCode} ${e.teacherCode||''} ${e.department}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  const save=async(emp:Employee)=>{try{await api('saveEmployee',{employee:emp});setEditing(null);load()}catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ')}};
  return <>
    <div className="page-header"><div><h1>الموظفون والمعلمون</h1><p>المعلم موظف واحد داخل النظام، وكود المعلم يستخدم للربط بالجدول فقط.</p></div><button className="btn btn-primary" onClick={()=>setEditing({...emptyEmployee})}><Plus size={16}/> إضافة موظف</button></div>
    {error&&<div className="alert alert-danger" style={{marginBottom:12}}>{error}</div>}
    <div className="card panel"><div className="toolbar"><div className="field"><label>بحث</label><div style={{position:'relative'}}><Search size={16} style={{position:'absolute',right:11,top:12,color:'#94a3b8'}}/><input className="input" style={{paddingRight:34}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="الاسم، كود الموظف، كود المعلم..."/></div></div></div>
    <div className="table-wrap"><table><thead><tr><th>كود الموظف</th><th>الاسم</th><th>الوظيفة</th><th>القسم</th><th>كود المعلم</th><th>الحالة</th><th></th></tr></thead><tbody>{filtered.map(e=><tr key={e.id}><td>{e.employeeCode}</td><td><strong>{e.name}</strong></td><td>{e.jobTitle}</td><td>{e.department}</td><td>{e.teacherCode||'—'}</td><td><span className={`badge ${e.status==='Active'?'badge-success':'badge-muted'}`}>{e.status==='Active'?'نشط':'غير نشط'}</span></td><td><div className="actions"><button className="btn btn-light btn-sm" onClick={()=>setEditing({...e})}>تعديل</button>{e.isTeacher&&<button className="btn btn-warning btn-sm" onClick={()=>setPinEmp(e)}><KeyRound size={13}/> PIN</button>}</div></td></tr>)}</tbody></table></div></div>
    {editing&&<EmployeeForm item={editing} onClose={()=>setEditing(null)} onSave={save}/>} {pinEmp&&<TeacherPin employee={pinEmp} onClose={()=>setPinEmp(null)}/>} 
  </>;
}
function EmployeeForm({item,onClose,onSave}:{item:Employee;onClose:()=>void;onSave:(e:Employee)=>void}){const[f,setF]=useState(item);return <Modal title={f.id?'تعديل الموظف':'إضافة موظف'} onClose={onClose}><div className="grid grid-2 form-grid"><div className="field"><label>الاسم</label><input className="input" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></div><div className="field"><label>كود الموظف</label><input className="input" value={f.employeeCode} onChange={e=>setF({...f,employeeCode:e.target.value})}/></div><div className="field"><label>المسمى الوظيفي</label><input className="input" value={f.jobTitle} onChange={e=>setF({...f,jobTitle:e.target.value})}/></div><div className="field"><label>القسم</label><input className="input" value={f.department} onChange={e=>setF({...f,department:e.target.value})}/></div><div className="field"><label>هل هو معلم؟</label><select className="select" value={f.isTeacher?'yes':'no'} onChange={e=>setF({...f,isTeacher:e.target.value==='yes'})}><option value="no">لا</option><option value="yes">نعم</option></select></div><div className="field"><label>كود المعلم</label><input className="input" disabled={!f.isTeacher} value={f.teacherCode||''} onChange={e=>setF({...f,teacherCode:e.target.value.toUpperCase()})}/></div></div><div className="actions" style={{marginTop:18}}><button className="btn btn-primary" onClick={()=>onSave({...f,id:f.id||`EMP-${Date.now()}`})}>حفظ</button><button className="btn btn-light" onClick={onClose}>إلغاء</button></div></Modal>}
function TeacherPin({employee,onClose}:{employee:Employee;onClose:()=>void}){const[pin,setPin]=useState('');const[msg,setMsg]=useState<string|null>(null);const save=async()=>{try{await api('setTeacherPin',{employeeId:employee.id,pin});setMsg('تم ضبط PIN للمعلم بنجاح.');setPin('')}catch(e){setMsg(e instanceof Error?e.message:'تعذر الحفظ')}};return <Modal title={`ضبط PIN — ${employee.name}`} onClose={onClose}><div className="alert alert-warning">كود المعلم هو هوية وليس كلمة مرور. الـPIN لا يُحفظ في المتصفح.</div><div className="field" style={{marginTop:14}}><label>PIN جديد (6 أرقام على الأقل)</label><input className="input" type="password" value={pin} onChange={e=>setPin(e.target.value)}/></div>{msg&&<div className="alert alert-success" style={{marginTop:10}}>{msg}</div>}<button className="btn btn-primary" style={{marginTop:14}} onClick={save}>حفظ PIN</button></Modal>}
