import React, { useEffect, useState } from 'react';
import { api } from '../lib/api';
import type { SessionUser, TimetableBootstrap } from '../types';
import { WeeklyGrid } from '../modules/timetable/WeeklyGrid';
import { TeacherLoadPanel } from '../modules/timetable/TeacherLoadPanel';
import { ReservePanel } from '../modules/timetable/ReservePanel';
import { SupervisionPanel } from '../modules/timetable/SupervisionPanel';
import { ExamsPanel } from '../modules/timetable/ExamsPanel';
import { CoveragePanel } from '../modules/timetable/CoveragePanel';
import { ImportPanel } from '../modules/timetable/ImportPanel';
import { SettingsPanel } from '../modules/timetable/SettingsPanel';
import { AvailabilityPanel } from '../modules/timetable/AvailabilityPanel';

type Tab='weekly'|'coverage'|'load'|'availability'|'reserve'|'supervision'|'exams'|'import'|'settings';
export function TimetablePage({user}:{user:SessionUser}){const[data,setData]=useState<TimetableBootstrap|null>(null);const[tab,setTab]=useState<Tab>('weekly');const[error,setError]=useState<string|null>(null);const load=()=>api<TimetableBootstrap>('timetableBootstrap').then(setData).catch(e=>setError(e.message));useEffect(load,[]);if(error)return <div className="alert alert-danger">{error}</div>;if(!data)return <div className="card panel">جارِ تحميل وحدة الجدول...</div>;const tabs:Array<[Tab,string,string[]]>=[['weekly','الجدول الأسبوعي',['Admin','SchoolDirector','TeacherAffairs','StudentAffairs','QualityOfficer','Viewer']],['coverage','مطابقة 39 حصة',['Admin','SchoolDirector','TeacherAffairs','StudentAffairs','QualityOfficer','Viewer']],['load','أنصبة المعلمين',['Admin','SchoolDirector','TeacherAffairs','QualityOfficer']],['availability','إتاحة المعلمين',['Admin','SchoolDirector','TeacherAffairs']],['reserve','الاحتياطي',['Admin','SchoolDirector','TeacherAffairs']],['supervision','الإشراف',['Admin','SchoolDirector','TeacherAffairs']],['exams','الامتحانات',['Admin','SchoolDirector','TeacherAffairs','StudentAffairs']],['import','استيراد Excel',['Admin','SchoolDirector','TeacherAffairs']],['settings','الإعدادات',['Admin','SchoolDirector','TeacherAffairs']]];return <><div className="page-header"><div><h1>الجدول المدرسي</h1><p>الجدول، النصاب، الاحتياطي، الإشراف، الامتحانات والخطة الدراسية في وحدة واحدة.</p></div><div className="badge badge-info">{data.config.academicYearName} — {data.config.termName}</div></div><div className="tabs">{tabs.filter(x=>x[2].includes(user.role)).map(([id,label])=><button key={id} className={`tab ${tab===id?'active':''}`} onClick={()=>setTab(id)}>{label}</button>)}</div>{tab==='weekly'&&<WeeklyGrid data={data} onReload={load}/>} {tab==='coverage'&&<CoveragePanel reports={data.curriculumCoverage}/>} {tab==='load'&&<TeacherLoadPanel loads={data.teacherLoads}/>} {tab==='availability'&&<AvailabilityPanel data={data} onReload={load}/>} {tab==='reserve'&&<ReservePanel data={data} onReload={load}/>} {tab==='supervision'&&<SupervisionPanel data={data} onReload={load}/>} {tab==='exams'&&<ExamsPanel data={data} onReload={load}/>} {tab==='import'&&<ImportPanel onReload={load}/>} {tab==='settings'&&<SettingsPanel config={data.config} onReload={load}/>}</>}
