import React, { useRef, useState } from 'react';
import * as XLSX from 'xlsx';
import type { CycleWeek, ScheduleImportRow, ScheduleImportValidation } from '../../types';
import { api } from '../../lib/api';

export function ImportPanel({onReload}:{onReload:()=>void}){const input=useRef<HTMLInputElement>(null);const[validation,setValidation]=useState<ScheduleImportValidation|null>(null);const[rows,setRows]=useState<ScheduleImportRow[]>([]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState<string|null>(null);
const read=async(file:File)=>{setBusy(true);setMsg(null);try{const buf=await file.arrayBuffer();const wb=XLSX.read(buf);const ws=wb.Sheets[wb.SheetNames[0]];const raw:any[]=XLSX.utils.sheet_to_json(ws,{defval:''});const parsed=raw.map((r,i)=>({rowNumber:i+2,dayOfWeek:String(r['اليوم']||r.Day||'').trim(),periodNumber:Number(r['الحصة']||r.Period||0),gradeName:String(r['الصف']||r.Grade||'').trim(),classroomName:String(r['الفصل']||r.Classroom||'').trim(),subjectName:String(r['المادة']||r.Subject||'').trim(),teacherCode:String(r['كود المعلم']||r.TeacherCode||'').trim().toUpperCase(),teacherName:String(r['اسم المعلم']||r.TeacherName||'').trim(),roomName:String(r['القاعة']||r.Room||'').trim(),cycleWeek:(String(r['أسبوع الخطة']||r.CycleWeek||'ALL').toUpperCase()||'ALL') as CycleWeek}));setRows(parsed);setValidation(await api<ScheduleImportValidation>('validateScheduleImport',{rows:parsed}))}catch(e){setMsg(e instanceof Error?e.message:'تعذر قراءة الملف')}finally{setBusy(false)}};
const commit=async()=>{if(!validation||validation.invalidRows>0)return;setBusy(true);try{await api('commitScheduleImport',{rows});setMsg('تم اعتماد الاستيراد بنجاح بدون تكرار الصفوف الحالية.');onReload()}catch(e){setMsg(e instanceof Error?e.message:'تعذر الاعتماد')}finally{setBusy(false)}};
return <div className="card panel"><div className="panel-header"><h3>استيراد الجدول من Excel / CSV</h3><button className="btn btn-primary btn-sm" onClick={()=>input.current?.click()}>اختيار ملف</button><input ref={input} type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>e.target.files?.[0]&&read(e.target.files[0])}/></div><div className="alert alert-warning">المطابقة الأساسية تتم بكود المعلم. المعلم أو الفصل أو المادة غير المعروفة تمنع اعتماد الصف.</div>{busy&&<div className="empty">جارِ الفحص...</div>}{msg&&<div className={msg.includes('تم')?'alert alert-success':'alert alert-danger'} style={{marginTop:12}}>{msg}</div>}{validation&&<><div className="grid grid-3" style={{marginTop:16}}><div className="card kpi"><div className="value">{validation.totalRows}</div><div className="label">إجمالي الصفوف</div></div><div className="card kpi"><div className="value" style={{color:'#059669'}}>{validation.validRows}</div><div className="label">صالح</div></div><div className="card kpi"><div className="value" style={{color:'#dc2626'}}>{validation.invalidRows}</div><div className="label">به أخطاء</div></div></div><div className="table-wrap" style={{marginTop:16}}><table><thead><tr><th>صف</th><th>اليوم</th><th>الحصة</th><th>الفصل</th><th>المادة</th><th>كود المعلم</th><th>الحالة</th></tr></thead><tbody>{validation.rows.map(r=><tr key={r.rowNumber}><td>{r.rowNumber}</td><td>{r.dayOfWeek}</td><td>{r.periodNumber}</td><td>{r.classroomName}</td><td>{r.subjectName}</td><td>{r.teacherCode}</td><td>{r.valid?<span className="badge badge-success">صالح</span>:<><span className="badge badge-danger">خطأ</span><div className="small" style={{color:'#be123c',marginTop:4}}>{r.errors.join(' — ')}</div></>}</td></tr>)}</tbody></table></div><button className="btn btn-indigo" style={{marginTop:14}} disabled={validation.invalidRows>0||busy} onClick={commit}>اعتماد الاستيراد</button></>}</div>}
