import React, { useState } from 'react';
import type { ReserveCandidate, TimetableBootstrap } from '../../types';
import { api } from '../../lib/api';
import { todayCairo, arabicDayName } from '../../lib/date';

export function ReservePanel({data,onReload}:{data:TimetableBootstrap;onReload:()=>void}){
  const teachers=data.employees.filter(e=>e.isTeacher&&e.status==='Active');
  const[date,setDate]=useState(todayCairo()); const[period,setPeriod]=useState(1); const[absent,setAbsent]=useState(teachers[0]?.id||''); const[classroom,setClassroom]=useState('1/1'); const[subject,setSubject]=useState(''); const[cands,setCands]=useState<ReserveCandidate[]>([]); const[msg,setMsg]=useState<string|null>(null);
  const find=async()=>{try{const r=await api<ReserveCandidate[]>('reserveCandidates',{date,dayOfWeek:arabicDayName(date),periodNumber:period,absentTeacherId:absent,classroomId:classroom,subjectName:subject});setCands(r)}catch(e){setMsg(e instanceof Error?e.message:'تعذر الترشيح')}};
  const assign=async(c:ReserveCandidate)=>{await api('saveReserve',{assignment:{date,dayOfWeek:arabicDayName(date),periodNumber:period,classroomId:classroom,classroomName:classroom,subjectId:`SUB-${subject}`,subjectName:subject,originalTeacherId:absent,originalTeacherName:teachers.find(t=>t.id===absent)?.name||'',substituteTeacherId:c.teacherId,substituteTeacherName:c.teacherName,reason:'غياب',status:'Scheduled'}});setMsg('تم إسناد الاحتياطي.');setCands([]);onReload()};
  const cancel=async(id:string)=>{if(!confirm('إلغاء حصة الاحتياطي مع الاحتفاظ بها في التاريخ؟'))return;await api('cancelReserve',{id});onReload()};
  return <div className="grid grid-2">
    <div className="card panel"><div className="panel-header"><h3>إسناد احتياطي</h3></div><div className="form-grid"><div className="field"><label>التاريخ</label><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>الحصة</label><select className="select" value={period} onChange={e=>setPeriod(Number(e.target.value))}>{data.config.periods.map(p=><option key={p.periodNumber} value={p.periodNumber}>الحصة {p.periodNumber}</option>)}</select></div><div className="field"><label>المعلم الغائب</label><select className="select" value={absent} onChange={e=>setAbsent(e.target.value)}>{teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className="field"><label>الفصل</label><input className="input" value={classroom} onChange={e=>setClassroom(e.target.value)}/></div><div className="field"><label>المادة</label><input className="input" value={subject} onChange={e=>setSubject(e.target.value)}/></div><button className="btn btn-primary" onClick={find}>ترشيح البدلاء</button>{msg&&<div className={msg.includes('تم')?'alert alert-success':'alert alert-danger'}>{msg}</div>}</div></div>
    <div className="card panel"><div className="panel-header"><h3>المرشحون</h3></div>{cands.length===0?<div className="empty">اضغط ترشيح البدلاء.</div>:<div className="table-wrap"><table><thead><tr><th>المعلم</th><th>الحمل</th><th>المتبقي</th><th>المادة</th><th></th></tr></thead><tbody>{cands.map(c=><tr key={c.teacherId}><td><strong>{c.teacherName}</strong><div className="small muted">احتياطي تاريخي: {c.historicalReserveCount}</div></td><td>{c.countedWeeklyPeriods}/30</td><td>{c.remainingCapacity}</td><td>{c.sameSubject?'نفس المادة':'بديل متاح'}</td><td>{c.eligible?<button className="btn btn-success btn-sm" onClick={()=>assign(c)}>إسناد</button>:<span className="badge badge-danger">{c.reason||'غير متاح'}</span>}</td></tr>)}</tbody></table></div>}</div>
    <div className="card panel" style={{gridColumn:'1/-1'}}><div className="panel-header"><h3>سجل الاحتياطي التاريخي</h3><span className="small muted">لا يتم مسحه مع بداية الأسبوع</span></div><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>الحصة</th><th>الفصل</th><th>المعلم الأصلي</th><th>البديل</th><th>الحالة</th><th></th></tr></thead><tbody>{data.reserves.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(r=><tr key={r.id}><td>{r.date}</td><td>{r.periodNumber}</td><td>{r.classroomName}</td><td>{r.originalTeacherName}</td><td>{r.substituteTeacherName}</td><td><span className={`badge ${r.status==='Cancelled'?'badge-muted':'badge-success'}`}>{r.status}</span></td><td>{r.status!=='Cancelled'&&<button className="btn btn-danger btn-sm" onClick={()=>cancel(r.id)}>إلغاء</button>}</td></tr>)}</tbody></table></div></div>
  </div>
}
