import React, { useState } from 'react';
import type { ScheduleBreak, ScheduleConfig } from '../../types';
import { api } from '../../lib/api';

const ALL_DAYS = ['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];

export function SettingsPanel({config,onReload}:{config:ScheduleConfig;onReload:()=>void}){
  const[cfg,setCfg]=useState<ScheduleConfig>(JSON.parse(JSON.stringify(config)));
  const[name,setName]=useState(''); const[start,setStart]=useState('10:20'); const[end,setEnd]=useState('10:40'); const[msg,setMsg]=useState<string|null>(null);
  const addBreak=()=>{if(!name.trim())return;const b:ScheduleBreak={id:`BRK-${Date.now()}`,name:name.trim(),startTime:start,endTime:end,isActive:true,sortOrder:cfg.breaks.length+1};setCfg({...cfg,breaks:[...cfg.breaks,b]});setName('')};
  const save=async()=>{try{await api('saveScheduleConfig',{config:cfg});setMsg('تم حفظ إعدادات الجدول.');onReload()}catch(e){setMsg(e instanceof Error?e.message:'تعذر الحفظ')}};
  const toggleDay=(d:string)=>setCfg({...cfg,studyDays:cfg.studyDays.includes(d)?cfg.studyDays.filter(x=>x!==d):[...cfg.studyDays,d]});
  const updatePeriod=(idx:number,field:'startTime'|'endTime',value:string)=>{const periods=[...cfg.periods];periods[idx]={...periods[idx],[field]:value};setCfg({...cfg,periods})};
  return <div className="grid grid-2">
    <div className="card panel"><div className="panel-header"><h3>سياسة النصاب والأسبوع</h3></div><div className="alert alert-success">القاعدة الأساسية: 25 ساعة = 1500 دقيقة = 30 حصة عند زمن حصة 50 دقيقة.</div><div className="form-grid" style={{marginTop:14}}><div className="field"><label>زمن الحصة بالدقائق</label><input className="input" type="number" value={cfg.teacherLoadPolicy.defaultPeriodMinutes} onChange={e=>{const d=Number(e.target.value)||50;setCfg({...cfg,teacherLoadPolicy:{...cfg.teacherLoadPolicy,defaultPeriodMinutes:d,weeklyPeriodLimit:Math.floor(cfg.teacherLoadPolicy.weeklyMinutesLimit/d)}})}}/></div><div className="field"><label>حد الدقائق الأسبوعي</label><input className="input" type="number" value={cfg.teacherLoadPolicy.weeklyMinutesLimit} onChange={e=>setCfg({...cfg,teacherLoadPolicy:{...cfg.teacherLoadPolicy,weeklyMinutesLimit:Number(e.target.value)}})}/></div><div className="field"><label>الحد الأسبوعي بالحصة</label><input className="input" type="number" value={cfg.teacherLoadPolicy.weeklyPeriodLimit} onChange={e=>setCfg({...cfg,teacherLoadPolicy:{...cfg.teacherLoadPolicy,weeklyPeriodLimit:Number(e.target.value)}})}/></div><div className="field"><label>تاريخ بداية أسبوع A</label><input className="input" type="date" value={cfg.cycleAnchorDate} onChange={e=>setCfg({...cfg,cycleAnchorDate:e.target.value})}/></div><label className="small"><input type="checkbox" checked={cfg.teacherLoadPolicy.reserveCountsTowardLoad} onChange={e=>setCfg({...cfg,teacherLoadPolicy:{...cfg.teacherLoadPolicy,reserveCountsTowardLoad:e.target.checked}})}/> احتساب الاحتياطي ضمن النصاب</label><label className="small"><input type="checkbox" checked={cfg.teacherLoadPolicy.supervisionCountsTowardLoad} onChange={e=>setCfg({...cfg,teacherLoadPolicy:{...cfg.teacherLoadPolicy,supervisionCountsTowardLoad:e.target.checked}})}/> احتساب الإشراف ضمن النصاب</label></div></div>
    <div className="card panel"><div className="panel-header"><h3>أيام الدراسة</h3></div><div className="feature-chips">{ALL_DAYS.map(d=><label className="chip" key={d} style={{cursor:'pointer'}}><input type="checkbox" checked={cfg.studyDays.includes(d)} onChange={()=>toggleDay(d)}/> {d}</label>)}</div><div className="small muted" style={{marginTop:10}}>ترتيب الأيام في العرض يتبع ترتيب الحفظ داخل القائمة.</div></div>
    <div className="card panel"><div className="panel-header"><h3>الفترات والحصص</h3></div><div className="table-wrap"><table><thead><tr><th>الحصة</th><th>من</th><th>إلى</th></tr></thead><tbody>{cfg.periods.map((p,idx)=><tr key={p.periodNumber}><td>{p.periodNumber}</td><td><input className="input" type="time" value={p.startTime} onChange={e=>updatePeriod(idx,'startTime',e.target.value)}/></td><td><input className="input" type="time" value={p.endTime} onChange={e=>updatePeriod(idx,'endTime',e.target.value)}/></td></tr>)}</tbody></table></div></div>
    <div className="card panel"><div className="panel-header"><h3>الفسح المدرسية</h3></div>{cfg.breaks.map(b=><div key={b.id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'9px 0',borderBottom:'1px solid #eef2f7'}}><div><strong className="small">{b.name}</strong><div className="small muted">{b.startTime} - {b.endTime}</div></div><button className="btn btn-danger btn-sm" onClick={()=>setCfg({...cfg,breaks:cfg.breaks.filter(x=>x.id!==b.id)})}>حذف</button></div>)}<div className="grid grid-3" style={{marginTop:12}}><input className="input" placeholder="اسم الفسحة" value={name} onChange={e=>setName(e.target.value)}/><input className="input" type="time" value={start} onChange={e=>setStart(e.target.value)}/><input className="input" type="time" value={end} onChange={e=>setEnd(e.target.value)}/></div><button className="btn btn-light btn-sm" style={{marginTop:8}} onClick={addBreak}>+ إضافة فسحة</button></div>
    <div style={{gridColumn:'1/-1'}}>{msg&&<div className={msg.includes('تم')?'alert alert-success':'alert alert-danger'}>{msg}</div>}<button className="btn btn-primary" style={{marginTop:10}} onClick={save}>حفظ كل إعدادات الجدول</button></div>
  </div>
}
