import React, { useState } from 'react';
import type { TimetableBootstrap } from '../../types';
import { api } from '../../lib/api';
import { arabicDayName, todayCairo } from '../../lib/date';

export function SupervisionPanel({data,onReload}:{data:TimetableBootstrap;onReload:()=>void}){
  const teachers=data.employees.filter(e=>e.isTeacher&&e.status==='Active');
  const[date,setDate]=useState(todayCairo()); const[teacherId,setTeacherId]=useState(teachers[0]?.id||''); const[locationId,setLocationId]=useState(data.supervisionLocations[0]?.id||''); const[shift,setShift]=useState('BREAK_1'); const[period,setPeriod]=useState<number|''>(''); const[msg,setMsg]=useState<string|null>(null); const[newLoc,setNewLoc]=useState('');
  const day=arabicDayName(date); const daily=data.supervisions.filter(a=>a.date===date&&a.status!=='Cancelled');
  const save=async()=>{const t=teachers.find(x=>x.id===teacherId);const l=data.supervisionLocations.find(x=>x.id===locationId);if(!t||!l)return;try{await api('saveSupervision',{assignment:{date,dayOfWeek:day,periodNumber:period===''?undefined:Number(period),locationId,locationName:l.name,teacherId,teacherName:t.name,teacherCode:t.teacherCode||'',shift,status:'Scheduled'}});setMsg('تم حفظ تكليف الإشراف.');onReload()}catch(e){setMsg(e instanceof Error?e.message:'تعذر الحفظ')}};
  const addLocation=async()=>{if(!newLoc.trim())return;await api('saveSupervisionLocation',{location:{name:newLoc.trim(),isActive:true,sortOrder:data.supervisionLocations.length+1}});setNewLoc('');onReload()};
  return <div className="grid grid-2">
    <div className="card panel"><div className="panel-header"><h3>تكليف إشراف</h3></div><div className="form-grid"><div className="field"><label>التاريخ</label><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>المعلم</label><select className="select" value={teacherId} onChange={e=>setTeacherId(e.target.value)}>{teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className="field"><label>الموقع</label><select className="select" value={locationId} onChange={e=>setLocationId(e.target.value)}>{data.supervisionLocations.filter(l=>l.isActive).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><div className="field"><label>الفترة</label><select className="select" value={shift} onChange={e=>setShift(e.target.value)}><option value="MORNING">طابور الصباح</option><option value="BREAK_1">الفسحة الأولى</option><option value="BREAK_2">الفسحة الثانية</option><option value="DISMISSAL">الانصراف</option><option value="PERIOD">أثناء حصة</option></select></div>{shift==='PERIOD'&&<div className="field"><label>رقم الحصة</label><select className="select" value={period} onChange={e=>setPeriod(Number(e.target.value))}><option value="">اختر</option>{data.config.periods.map(p=><option key={p.periodNumber} value={p.periodNumber}>{p.periodNumber}</option>)}</select></div>}<button className="btn btn-primary" onClick={save}>حفظ التكليف</button>{msg&&<div className={msg.includes('تم')?'alert alert-success':'alert alert-danger'}>{msg}</div>}</div><div style={{borderTop:'1px solid #eef2f7',marginTop:16,paddingTop:12}}><div className="small" style={{fontWeight:800,marginBottom:7}}>إضافة موقع إشراف</div><div className="actions"><input className="input" placeholder="مثال: الدور الثالث" value={newLoc} onChange={e=>setNewLoc(e.target.value)}/><button className="btn btn-light btn-sm" onClick={addLocation}>إضافة</button></div></div></div>
    <div className="card panel"><div className="panel-header"><h3>إشراف يوم {day}</h3></div><div className="table-wrap"><table><thead><tr><th>المعلم</th><th>الموقع</th><th>الفترة</th><th></th></tr></thead><tbody>{daily.map(x=><tr key={x.id}><td>{x.teacherName}</td><td>{x.locationName}</td><td>{x.shift}{x.periodNumber?` — حصة ${x.periodNumber}`:''}</td><td><button className="btn btn-danger btn-sm" onClick={async()=>{await api('deleteSupervision',{id:x.id});onReload()}}>إلغاء</button></td></tr>)}</tbody></table></div></div>
  </div>
}
