import React, { useMemo, useState } from 'react';
import type { ScheduleItem, TimetableBootstrap } from '../../types';
import { api } from '../../lib/api';
import { Modal } from '../../components/Modal';

export function WeeklyGrid({ data, onReload }: { data: TimetableBootstrap; onReload: () => void }) {
  const [classroom, setClassroom] = useState(data.schedule[0]?.classroomId || '1/1');
  const [cycle, setCycle] = useState<'ALL'|'A'|'B'>('ALL');
  const [editing, setEditing] = useState<ScheduleItem|null>(null);
  const days = data.config.studyDays;
  const periods = data.config.periods;
  const classrooms = useMemo(()=>Array.from(new Map(data.schedule.map(s=>[s.classroomId,s.classroomName])).entries()),[data.schedule]);
  const items = data.schedule.filter(s=>s.classroomId===classroom && (cycle==='ALL'||s.cycleWeek==='ALL'||s.cycleWeek===cycle));
  const at=(day:string,p:number)=>items.find(s=>s.dayOfWeek===day&&s.periodNumber===p);
  const del=async(id:string)=>{if(!confirm('حذف هذه الحصة؟'))return;await api('deleteScheduleItem',{id});onReload()};
  return <div className="card panel">
    <div className="panel-header"><h3>الجدول الأسبوعي</h3><div className="actions"><select className="select" value={classroom} onChange={e=>setClassroom(e.target.value)}>{classrooms.length?classrooms.map(([id,name])=><option key={id} value={id}>{name}</option>):<option value="1/1">1/1</option>}</select><select className="select" value={cycle} onChange={e=>setCycle(e.target.value as any)}><option value="ALL">كل الأسابيع</option><option value="A">أسبوع A</option><option value="B">أسبوع B</option></select></div></div>
    <div style={{overflow:'auto'}}><div className="week-grid"><div className="head">اليوم / الحصة</div>{periods.map(p=><div className="head" key={p.periodNumber}>{p.periodNumber}<div className="small muted">{p.startTime}</div></div>)}{days.map(day=><React.Fragment key={day}><div className="day">{day}</div>{periods.map(p=>{const item=at(day,p.periodNumber);return <div key={`${day}-${p.periodNumber}`}>{item?<div className="lesson"><strong>{item.subjectName}</strong><span>{item.teacherName}</span><span>{item.roomName||''}</span><div className="actions" style={{marginTop:6}}><button className="btn btn-light btn-sm" onClick={()=>setEditing(item)}>تعديل</button><button className="btn btn-danger btn-sm" onClick={()=>del(item.id)}>حذف</button></div></div>:<button className="btn btn-light btn-sm" onClick={()=>setEditing(newItem(day,p.periodNumber,p.startTime,p.endTime,classroom,data))}>+ حصة</button>}</div>})}</React.Fragment>)}</div></div>
    {editing&&<ScheduleForm item={editing} data={data} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);onReload()}}/>}
  </div>
}
function newItem(day:string,p:number,start:string,end:string,classroom:string,data:TimetableBootstrap):ScheduleItem{const cls=data.schedule.find(s=>s.classroomId===classroom);return{id:'',academicYearId:data.config.academicYearId,academicYearName:data.config.academicYearName,termId:data.config.termId,termName:data.config.termName,dayOfWeek:day,periodNumber:p,startTime:start,endTime:end,gradeId:cls?.gradeId||'G1',gradeName:cls?.gradeName||'الصف الأول الثانوي',classroomId:classroom,classroomName:cls?.classroomName||classroom,subjectId:'',subjectName:'',teacherId:'',teacherName:'',teacherCode:'',cycleWeek:'ALL',status:'Draft',isLocked:false}}
function ScheduleForm({item,data,onClose,onSaved}:{item:ScheduleItem;data:TimetableBootstrap;onClose:()=>void;onSaved:()=>void}){const[f,setF]=useState(item);const teachers=data.employees.filter(e=>e.isTeacher&&e.status==='Active');const save=async()=>{await api('saveScheduleItem',{item:{...f,id:f.id||`SCH-${Date.now()}`}});onSaved()};return <Modal title={f.id?'تعديل الحصة':'إضافة حصة'} onClose={onClose}><div className="grid grid-2 form-grid"><div className="field"><label>المادة</label><input className="input" value={f.subjectName} onChange={e=>setF({...f,subjectName:e.target.value,subjectId:f.subjectId||`SUB-${e.target.value}`})}/></div><div className="field"><label>المعلم</label><select className="select" value={f.teacherId} onChange={e=>{const t=teachers.find(x=>x.id===e.target.value);setF({...f,teacherId:t?.id||'',teacherName:t?.name||'',teacherCode:t?.teacherCode||''})}}><option value="">اختر</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.name} ({t.teacherCode})</option>)}</select></div><div className="field"><label>القاعة</label><input className="input" value={f.roomName||''} onChange={e=>setF({...f,roomName:e.target.value})}/></div><div className="field"><label>دورة الأسبوع</label><select className="select" value={f.cycleWeek} onChange={e=>setF({...f,cycleWeek:e.target.value as any})}><option value="ALL">كل أسبوع</option><option value="A">أسبوع A</option><option value="B">أسبوع B</option></select></div><div className="field"><label>الحالة</label><select className="select" value={f.status} onChange={e=>setF({...f,status:e.target.value as any})}><option value="Draft">مسودة</option><option value="UnderReview">تحت المراجعة</option><option value="Approved">معتمد</option><option value="Published">منشور</option><option value="Archived">مؤرشف</option></select></div></div><div className="actions" style={{marginTop:18}}><button className="btn btn-indigo" onClick={save}>حفظ</button><button className="btn btn-light" onClick={onClose}>إلغاء</button></div></Modal>}
